my $username = getlogin;
print($username,"\n");

print("C:\\Users\\$username\\test.txt\n");
$write = "C:\\Users\\$username\\test.txt";

@array_of_name = (Karlitos,Jimmy,Willy);

open(my $fh, '>', $write);
foreach $name_in (@array_of_name){
	print($name);
	print($fh "$name_in\n");
	}


# open(my $fh, '>', $write);
# print $fh "My first report generated by perl\n";
# close $fh;
# print "done\n";